//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/CofrontationInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CofrontationInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CofrontationInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CofrontationInput"",
    ""maps"": [
        {
            ""name"": ""PlayerInput"",
            ""id"": ""24b4597a-21b1-4eeb-aa24-182bdcea8ca7"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""7f16295c-60ea-40d2-a358-5d610aad9c8b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseDelta"",
                    ""type"": ""Value"",
                    ""id"": ""e7a80c0c-090f-48f0-8f40-71dcbe0737e2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ZoomCamera"",
                    ""type"": ""Value"",
                    ""id"": ""33fbe121-1e2c-4e8f-aa86-5facf48a98c6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DebugBuildingMine"",
                    ""type"": ""Button"",
                    ""id"": ""bea2876e-f07d-442f-aabb-7b7e6bc79f89"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugBuildingFarm"",
                    ""type"": ""Button"",
                    ""id"": ""8fca4daa-4630-439f-9295-eeabefed902a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugBuildingGrass"",
                    ""type"": ""Button"",
                    ""id"": ""f425c409-aef4-48a9-b288-1c9fb48e9280"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseDeltaStatement"",
                    ""type"": ""Button"",
                    ""id"": ""b3b753ae-55b4-49ee-83d5-d0c898a92a5d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""b8eb02a6-2cf1-4e28-a984-b7c833466a91"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""82acc4e0-90f7-44a1-972b-7f17f321fdb4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9af6471c-aa67-4b31-b5bf-1cc579be2eee"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""43a88e85-bc6b-4b5c-adcb-c323e8eb1d49"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ed943e61-9139-45a6-babe-73f07b0636bc"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""6c61a7ef-5dfc-4cb4-b5db-8fdd713c8f67"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b925d024-0c78-4a71-8914-ff2609ec2a2e"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ebd61e11-6ad3-4702-93c4-f6544f479a83"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""aa76575a-0693-443a-a071-f111041fae9c"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1181e584-0908-4ce2-9b13-146ffccfec5a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""76a5f2e3-209a-4ee8-9662-0d36ee53b0a7"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MouseDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""288fc6ed-f4a5-4571-98b4-740190186839"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""ZoomCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b3b0a28-1331-49af-9491-f79aa0e48942"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugBuildingMine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12be178e-dbb3-4a5d-aa9d-c79321a7497c"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugBuildingFarm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b59df22-c173-4265-b7ae-779019298227"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugBuildingFarm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a05830f2-18f7-402a-aa8f-d54cde22a6e7"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugBuildingGrass"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d01fec18-6761-46f6-beaf-08ed0e3f331d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugBuildingGrass"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75345528-4cdf-4557-b871-b1f7b85aa9bd"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MouseDeltaStatement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC"",
            ""bindingGroup"": ""PC"",
            ""devices"": []
        }
    ]
}");
        // PlayerInput
        m_PlayerInput = asset.FindActionMap("PlayerInput", throwIfNotFound: true);
        m_PlayerInput_Movement = m_PlayerInput.FindAction("Movement", throwIfNotFound: true);
        m_PlayerInput_MouseDelta = m_PlayerInput.FindAction("MouseDelta", throwIfNotFound: true);
        m_PlayerInput_ZoomCamera = m_PlayerInput.FindAction("ZoomCamera", throwIfNotFound: true);
        m_PlayerInput_DebugBuildingMine = m_PlayerInput.FindAction("DebugBuildingMine", throwIfNotFound: true);
        m_PlayerInput_DebugBuildingFarm = m_PlayerInput.FindAction("DebugBuildingFarm", throwIfNotFound: true);
        m_PlayerInput_DebugBuildingGrass = m_PlayerInput.FindAction("DebugBuildingGrass", throwIfNotFound: true);
        m_PlayerInput_MouseDeltaStatement = m_PlayerInput.FindAction("MouseDeltaStatement", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInput
    private readonly InputActionMap m_PlayerInput;
    private IPlayerInputActions m_PlayerInputActionsCallbackInterface;
    private readonly InputAction m_PlayerInput_Movement;
    private readonly InputAction m_PlayerInput_MouseDelta;
    private readonly InputAction m_PlayerInput_ZoomCamera;
    private readonly InputAction m_PlayerInput_DebugBuildingMine;
    private readonly InputAction m_PlayerInput_DebugBuildingFarm;
    private readonly InputAction m_PlayerInput_DebugBuildingGrass;
    private readonly InputAction m_PlayerInput_MouseDeltaStatement;
    public struct PlayerInputActions
    {
        private @CofrontationInput m_Wrapper;
        public PlayerInputActions(@CofrontationInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerInput_Movement;
        public InputAction @MouseDelta => m_Wrapper.m_PlayerInput_MouseDelta;
        public InputAction @ZoomCamera => m_Wrapper.m_PlayerInput_ZoomCamera;
        public InputAction @DebugBuildingMine => m_Wrapper.m_PlayerInput_DebugBuildingMine;
        public InputAction @DebugBuildingFarm => m_Wrapper.m_PlayerInput_DebugBuildingFarm;
        public InputAction @DebugBuildingGrass => m_Wrapper.m_PlayerInput_DebugBuildingGrass;
        public InputAction @MouseDeltaStatement => m_Wrapper.m_PlayerInput_MouseDeltaStatement;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerInputActions instance)
        {
            if (m_Wrapper.m_PlayerInputActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMovement;
                @MouseDelta.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMouseDelta;
                @MouseDelta.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMouseDelta;
                @MouseDelta.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMouseDelta;
                @ZoomCamera.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnZoomCamera;
                @ZoomCamera.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnZoomCamera;
                @ZoomCamera.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnZoomCamera;
                @DebugBuildingMine.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnDebugBuildingMine;
                @DebugBuildingMine.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnDebugBuildingMine;
                @DebugBuildingMine.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnDebugBuildingMine;
                @DebugBuildingFarm.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnDebugBuildingFarm;
                @DebugBuildingFarm.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnDebugBuildingFarm;
                @DebugBuildingFarm.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnDebugBuildingFarm;
                @DebugBuildingGrass.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnDebugBuildingGrass;
                @DebugBuildingGrass.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnDebugBuildingGrass;
                @DebugBuildingGrass.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnDebugBuildingGrass;
                @MouseDeltaStatement.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMouseDeltaStatement;
                @MouseDeltaStatement.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMouseDeltaStatement;
                @MouseDeltaStatement.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMouseDeltaStatement;
            }
            m_Wrapper.m_PlayerInputActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @MouseDelta.started += instance.OnMouseDelta;
                @MouseDelta.performed += instance.OnMouseDelta;
                @MouseDelta.canceled += instance.OnMouseDelta;
                @ZoomCamera.started += instance.OnZoomCamera;
                @ZoomCamera.performed += instance.OnZoomCamera;
                @ZoomCamera.canceled += instance.OnZoomCamera;
                @DebugBuildingMine.started += instance.OnDebugBuildingMine;
                @DebugBuildingMine.performed += instance.OnDebugBuildingMine;
                @DebugBuildingMine.canceled += instance.OnDebugBuildingMine;
                @DebugBuildingFarm.started += instance.OnDebugBuildingFarm;
                @DebugBuildingFarm.performed += instance.OnDebugBuildingFarm;
                @DebugBuildingFarm.canceled += instance.OnDebugBuildingFarm;
                @DebugBuildingGrass.started += instance.OnDebugBuildingGrass;
                @DebugBuildingGrass.performed += instance.OnDebugBuildingGrass;
                @DebugBuildingGrass.canceled += instance.OnDebugBuildingGrass;
                @MouseDeltaStatement.started += instance.OnMouseDeltaStatement;
                @MouseDeltaStatement.performed += instance.OnMouseDeltaStatement;
                @MouseDeltaStatement.canceled += instance.OnMouseDeltaStatement;
            }
        }
    }
    public PlayerInputActions @PlayerInput => new PlayerInputActions(this);
    private int m_PCSchemeIndex = -1;
    public InputControlScheme PCScheme
    {
        get
        {
            if (m_PCSchemeIndex == -1) m_PCSchemeIndex = asset.FindControlSchemeIndex("PC");
            return asset.controlSchemes[m_PCSchemeIndex];
        }
    }
    public interface IPlayerInputActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnMouseDelta(InputAction.CallbackContext context);
        void OnZoomCamera(InputAction.CallbackContext context);
        void OnDebugBuildingMine(InputAction.CallbackContext context);
        void OnDebugBuildingFarm(InputAction.CallbackContext context);
        void OnDebugBuildingGrass(InputAction.CallbackContext context);
        void OnMouseDeltaStatement(InputAction.CallbackContext context);
    }
}
